// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.1
// source: utc_sys.proto

package utcsyncpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type APPParaHeartbeatReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SysTimezone   *int32                 `protobuf:"zigzag32,20,opt,name=sys_timezone,json=sysTimezone" json:"sys_timezone,omitempty"`
	SysTimezoneId *string                `protobuf:"bytes,21,opt,name=sys_timezone_id,json=sysTimezoneId" json:"sys_timezone_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APPParaHeartbeatReport) Reset() {
	*x = APPParaHeartbeatReport{}
	mi := &file_utc_sys_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APPParaHeartbeatReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APPParaHeartbeatReport) ProtoMessage() {}

func (x *APPParaHeartbeatReport) ProtoReflect() protoreflect.Message {
	mi := &file_utc_sys_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APPParaHeartbeatReport.ProtoReflect.Descriptor instead.
func (*APPParaHeartbeatReport) Descriptor() ([]byte, []int) {
	return file_utc_sys_proto_rawDescGZIP(), []int{0}
}

func (x *APPParaHeartbeatReport) GetSysTimezone() int32 {
	if x != nil && x.SysTimezone != nil {
		return *x.SysTimezone
	}
	return 0
}

func (x *APPParaHeartbeatReport) GetSysTimezoneId() string {
	if x != nil && x.SysTimezoneId != nil {
		return *x.SysTimezoneId
	}
	return ""
}

type SysUTCRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SysUTCRequest) Reset() {
	*x = SysUTCRequest{}
	mi := &file_utc_sys_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysUTCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysUTCRequest) ProtoMessage() {}

func (x *SysUTCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_utc_sys_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysUTCRequest.ProtoReflect.Descriptor instead.
func (*SysUTCRequest) Descriptor() ([]byte, []int) {
	return file_utc_sys_proto_rawDescGZIP(), []int{1}
}

type SysUTCRequestACK struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SysUtcTime    *uint32                `protobuf:"varint,1,opt,name=sys_utc_time,json=sysUtcTime" json:"sys_utc_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SysUTCRequestACK) Reset() {
	*x = SysUTCRequestACK{}
	mi := &file_utc_sys_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysUTCRequestACK) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysUTCRequestACK) ProtoMessage() {}

func (x *SysUTCRequestACK) ProtoReflect() protoreflect.Message {
	mi := &file_utc_sys_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysUTCRequestACK.ProtoReflect.Descriptor instead.
func (*SysUTCRequestACK) Descriptor() ([]byte, []int) {
	return file_utc_sys_proto_rawDescGZIP(), []int{2}
}

func (x *SysUTCRequestACK) GetSysUtcTime() uint32 {
	if x != nil && x.SysUtcTime != nil {
		return *x.SysUtcTime
	}
	return 0
}

type SysRTCInfoGet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SysRTCInfoGet) Reset() {
	*x = SysRTCInfoGet{}
	mi := &file_utc_sys_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysRTCInfoGet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysRTCInfoGet) ProtoMessage() {}

func (x *SysRTCInfoGet) ProtoReflect() protoreflect.Message {
	mi := &file_utc_sys_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysRTCInfoGet.ProtoReflect.Descriptor instead.
func (*SysRTCInfoGet) Descriptor() ([]byte, []int) {
	return file_utc_sys_proto_rawDescGZIP(), []int{3}
}

type SysRTCInfoGetACK struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SysUtcTime    *uint32                `protobuf:"varint,1,opt,name=sys_utc_time,json=sysUtcTime" json:"sys_utc_time,omitempty"`
	SysTimezone   *int32                 `protobuf:"zigzag32,2,opt,name=sys_timezone,json=sysTimezone" json:"sys_timezone,omitempty"`
	TimeType      *uint32                `protobuf:"varint,3,opt,name=time_type,json=timeType" json:"time_type,omitempty"`
	TimezoneId    *string                `protobuf:"bytes,4,opt,name=timezone_id,json=timezoneId" json:"timezone_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SysRTCInfoGetACK) Reset() {
	*x = SysRTCInfoGetACK{}
	mi := &file_utc_sys_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysRTCInfoGetACK) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysRTCInfoGetACK) ProtoMessage() {}

func (x *SysRTCInfoGetACK) ProtoReflect() protoreflect.Message {
	mi := &file_utc_sys_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysRTCInfoGetACK.ProtoReflect.Descriptor instead.
func (*SysRTCInfoGetACK) Descriptor() ([]byte, []int) {
	return file_utc_sys_proto_rawDescGZIP(), []int{4}
}

func (x *SysRTCInfoGetACK) GetSysUtcTime() uint32 {
	if x != nil && x.SysUtcTime != nil {
		return *x.SysUtcTime
	}
	return 0
}

func (x *SysRTCInfoGetACK) GetSysTimezone() int32 {
	if x != nil && x.SysTimezone != nil {
		return *x.SysTimezone
	}
	return 0
}

func (x *SysRTCInfoGetACK) GetTimeType() uint32 {
	if x != nil && x.TimeType != nil {
		return *x.TimeType
	}
	return 0
}

func (x *SysRTCInfoGetACK) GetTimezoneId() string {
	if x != nil && x.TimezoneId != nil {
		return *x.TimezoneId
	}
	return ""
}

type SysUTCSync struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SysUtcTime    *uint32                `protobuf:"varint,1,opt,name=sys_utc_time,json=sysUtcTime" json:"sys_utc_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SysUTCSync) Reset() {
	*x = SysUTCSync{}
	mi := &file_utc_sys_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysUTCSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysUTCSync) ProtoMessage() {}

func (x *SysUTCSync) ProtoReflect() protoreflect.Message {
	mi := &file_utc_sys_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysUTCSync.ProtoReflect.Descriptor instead.
func (*SysUTCSync) Descriptor() ([]byte, []int) {
	return file_utc_sys_proto_rawDescGZIP(), []int{5}
}

func (x *SysUTCSync) GetSysUtcTime() uint32 {
	if x != nil && x.SysUtcTime != nil {
		return *x.SysUtcTime
	}
	return 0
}

type SetCmdResultAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *int32                 `protobuf:"zigzag32,1,opt,name=result" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCmdResultAck) Reset() {
	*x = SetCmdResultAck{}
	mi := &file_utc_sys_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCmdResultAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCmdResultAck) ProtoMessage() {}

func (x *SetCmdResultAck) ProtoReflect() protoreflect.Message {
	mi := &file_utc_sys_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCmdResultAck.ProtoReflect.Descriptor instead.
func (*SetCmdResultAck) Descriptor() ([]byte, []int) {
	return file_utc_sys_proto_rawDescGZIP(), []int{6}
}

func (x *SetCmdResultAck) GetResult() int32 {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return 0
}

type SysTimezoneSync struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SysTimezone   *int32                 `protobuf:"zigzag32,1,opt,name=sys_timezone,json=sysTimezone" json:"sys_timezone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SysTimezoneSync) Reset() {
	*x = SysTimezoneSync{}
	mi := &file_utc_sys_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysTimezoneSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysTimezoneSync) ProtoMessage() {}

func (x *SysTimezoneSync) ProtoReflect() protoreflect.Message {
	mi := &file_utc_sys_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysTimezoneSync.ProtoReflect.Descriptor instead.
func (*SysTimezoneSync) Descriptor() ([]byte, []int) {
	return file_utc_sys_proto_rawDescGZIP(), []int{7}
}

func (x *SysTimezoneSync) GetSysTimezone() int32 {
	if x != nil && x.SysTimezone != nil {
		return *x.SysTimezone
	}
	return 0
}

type SysTimezoneIDSync struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimezoneId    *string                `protobuf:"bytes,1,opt,name=timezone_id,json=timezoneId" json:"timezone_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SysTimezoneIDSync) Reset() {
	*x = SysTimezoneIDSync{}
	mi := &file_utc_sys_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysTimezoneIDSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysTimezoneIDSync) ProtoMessage() {}

func (x *SysTimezoneIDSync) ProtoReflect() protoreflect.Message {
	mi := &file_utc_sys_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysTimezoneIDSync.ProtoReflect.Descriptor instead.
func (*SysTimezoneIDSync) Descriptor() ([]byte, []int) {
	return file_utc_sys_proto_rawDescGZIP(), []int{8}
}

func (x *SysTimezoneIDSync) GetTimezoneId() string {
	if x != nil && x.TimezoneId != nil {
		return *x.TimezoneId
	}
	return ""
}

var File_utc_sys_proto protoreflect.FileDescriptor

const file_utc_sys_proto_rawDesc = "" +
	"\n" +
	"\rutc_sys.proto\x12\x03utc\"c\n" +
	"\x16APPParaHeartbeatReport\x12!\n" +
	"\fsys_timezone\x18\x14 \x01(\x11R\vsysTimezone\x12&\n" +
	"\x0fsys_timezone_id\x18\x15 \x01(\tR\rsysTimezoneId\"\x0f\n" +
	"\rSysUTCRequest\"4\n" +
	"\x10SysUTCRequestACK\x12 \n" +
	"\fsys_utc_time\x18\x01 \x01(\rR\n" +
	"sysUtcTime\"\x0f\n" +
	"\rSysRTCInfoGet\"\x95\x01\n" +
	"\x10SysRTCInfoGetACK\x12 \n" +
	"\fsys_utc_time\x18\x01 \x01(\rR\n" +
	"sysUtcTime\x12!\n" +
	"\fsys_timezone\x18\x02 \x01(\x11R\vsysTimezone\x12\x1b\n" +
	"\ttime_type\x18\x03 \x01(\rR\btimeType\x12\x1f\n" +
	"\vtimezone_id\x18\x04 \x01(\tR\n" +
	"timezoneId\".\n" +
	"\n" +
	"SysUTCSync\x12 \n" +
	"\fsys_utc_time\x18\x01 \x01(\rR\n" +
	"sysUtcTime\")\n" +
	"\x0fSetCmdResultAck\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x11R\x06result\"4\n" +
	"\x0fSysTimezoneSync\x12!\n" +
	"\fsys_timezone\x18\x01 \x01(\x11R\vsysTimezone\"4\n" +
	"\x11SysTimezoneIDSync\x12\x1f\n" +
	"\vtimezone_id\x18\x01 \x01(\tR\n" +
	"timezoneId"

var (
	file_utc_sys_proto_rawDescOnce sync.Once
	file_utc_sys_proto_rawDescData []byte
)

func file_utc_sys_proto_rawDescGZIP() []byte {
	file_utc_sys_proto_rawDescOnce.Do(func() {
		file_utc_sys_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_utc_sys_proto_rawDesc), len(file_utc_sys_proto_rawDesc)))
	})
	return file_utc_sys_proto_rawDescData
}

var file_utc_sys_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_utc_sys_proto_goTypes = []any{
	(*APPParaHeartbeatReport)(nil), // 0: utc.APPParaHeartbeatReport
	(*SysUTCRequest)(nil),          // 1: utc.SysUTCRequest
	(*SysUTCRequestACK)(nil),       // 2: utc.SysUTCRequestACK
	(*SysRTCInfoGet)(nil),          // 3: utc.SysRTCInfoGet
	(*SysRTCInfoGetACK)(nil),       // 4: utc.SysRTCInfoGetACK
	(*SysUTCSync)(nil),             // 5: utc.SysUTCSync
	(*SetCmdResultAck)(nil),        // 6: utc.SetCmdResultAck
	(*SysTimezoneSync)(nil),        // 7: utc.SysTimezoneSync
	(*SysTimezoneIDSync)(nil),      // 8: utc.SysTimezoneIDSync
}
var file_utc_sys_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_utc_sys_proto_init() }
func file_utc_sys_proto_init() {
	if File_utc_sys_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_utc_sys_proto_rawDesc), len(file_utc_sys_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_utc_sys_proto_goTypes,
		DependencyIndexes: file_utc_sys_proto_depIdxs,
		MessageInfos:      file_utc_sys_proto_msgTypes,
	}.Build()
	File_utc_sys_proto = out.File
	file_utc_sys_proto_goTypes = nil
	file_utc_sys_proto_depIdxs = nil
}
